version: "1"
services:
  db-postgres:
    image: postgres:14.5
    restart: unless-stopped
    hostname: postgres
    container_name: uuEduKit-db
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment: 
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - my-bridge-network
  frontend:
    container_name: client
    platform: linux/amd64
    image: uuEduKit/frontend
    build: ./client
    ports:
      - 3000:3000
    env_file:
      - .env
    environment:
      - API_URL
    networks:
      - my-bridge-network
  backend:
    container_name: backend
    platform: linux/amd64
    image: uuEduKit/backend
    build: ./server
    ports:
      - 80:3001
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_USERNAME
      - POSTGRES_HOST
      - POSTGRES_DATABASE
    networks:
      - my-bridge-network

networks:
  my-bridge-network:
    driver: bridge

volumes:
  pgdata: