version: "3"
services:
  db-ue-edu-kit-postgres:
    image: postgres:14.5
    restart: unless-stopped
    container_name: uu-edukit-db
    volumes:
      - pgUuEduKitData:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment: 
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    networks:
      - default
volumes:
  pgUuEduKitData: